<?php

namespace AppBundle\Repository;

use AppBundle\Entity\BusEntry;
use AppBundle\Entity\BusStop;
use Doctrine\ORM\EntityRepository;

/**
 * BusEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusEntryRepository extends EntityRepository
{
    public function findBusEntries(BusStop $busStop)
    {
        $day = date('w');
        if ($day == 6) {
            $type = BusEntry::TYPE_SATURDAY;
        } else if ($day == 7) {
            $type = BusEntry::TYPE_SUNDAY;
        } else {
            $type = BusEntry::TYPE_NORMAL;
        }
        return $this->createQueryBuilder("be")
            ->where("unix_timestamp(be.stopAt) - unix_timestamp(CURRENT_TIMESTAMP()) > 0")
            ->andWhere("unix_timestamp(be.stopAt) - unix_timestamp(CURRENT_TIMESTAMP()) <= 300")
            ->andWhere("be.busStop = :busStop")
            ->andWhere('be.type = :type')
            ->setParameter("busStop", $busStop)
            ->setParameter("type", $type)
            ->orderBy("be.stopAt", "ASC")
            ->getQuery()->getResult();

    }
}
